service: iSee-retrieval
frameworkVersion: '2 || 3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  hello:
    handler: handler.retrieval
    events:
      - httpApi:
          path: /back-end/retrieval
          method: post
